####################################################################################################
# Async Jobs
####################################################################################################
job:
  executor:
    common:
      corePoolSize: 4
      maxPoolSize: 6
